- name: Variables from files
  hosts: localhost
  vars_files:
  - variables.yml
  tasks:
  - name: Printing variables from files
    debug:
      msg: "Nameis : {{NAME}}, City is : {{CITY}}"
  - name: Printing List variables from files
    debug:
      msg: "Packages are : {{packages}}, 1st package is : {{packages[0]}}"