- name: Checking user and create it if not exit
  hosts: web
  become: yes
  vars_prompt:
    name: USER
    prompt: Please enter user name?
    private: false
  tasks:
  - name: Checking user is already existed or not
    command: id {{USER}}
    register: output
    ignore_errors: true
  - name: print output 
    debug:
      msg: "printing output is : {{output}}"
  - name: Create a user if not existed
    user:
      name: "{{USER}}"
    when: output.rc != 0