- name: Handlers expmple
  hosts: web
  become: yes
  vars:
    package: nginx
  tasks:
  - name: Installing package
    yum: 
      name: package
      state: installed
    notify: 
    - starting nginx
  handlers:
  - name: starting nginx
    service:
      name: nginx
      state: started