- name: Installing packages using loops
  hosts: all
  become: yes
  tasks: 
  - name: Installing list of packages
    yum:
      name: "{{item}}"
      state: installed
    loop:
    - postfix
    - mailx
    - curl
    - zip