- name: Installing packages using Advance list of map
  hosts: all
  beccome: yes
  tasks:
  - name: Installing or removing packages
    yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'postfix' , state: 'absent'}
    - {name: 'mailx' , state: 'installed'}
    - {name: 'curl' , state: 'absent'}
    - {name: 'zip' , state: 'absent'}